local helper = require("helper")

describe("FileUtil", function()
    local dir, FileUtil

    before_each(function()
        helper.reset()
        dir = helper.tmpdir("files")
        FileUtil = require("util.fileutil")
    end)

    after_each(helper.cleanup)

    describe("getSize", function()
        it("returns the size of a file in bytes", function()
            helper.writeFile(dir .. "/book.epub", "12345")
            assert.are.equal(5, FileUtil.getSize(dir .. "/book.epub"))
        end)

        it("returns 0 for missing files and invalid paths", function()
            assert.are.equal(0, FileUtil.getSize(dir .. "/missing.epub"))
            assert.are.equal(0, FileUtil.getSize(nil))
        end)
    end)

    describe("createFile", function()
        it("writes binary data", function()
            FileUtil.createFile(dir .. "/cover.jpg", "\255\216\255")
            assert.are.equal("\255\216\255", helper.readFile(dir .. "/cover.jpg"))
        end)

        it("returns nil when the file cannot be created", function()
            assert.is_nil(FileUtil.createFile(dir .. "/missing/cover.jpg", "data"))
        end)
    end)

    describe("readFile", function()
        it("returns the trimmed contents", function()
            helper.writeFile(dir .. "/version.txt", "0.3\n")
            assert.are.equal("0.3", FileUtil.readFile(dir .. "/version.txt"))
        end)

        it("returns nil for missing files and invalid paths", function()
            assert.is_nil(FileUtil.readFile(dir .. "/missing.txt"))
            assert.is_nil(FileUtil.readFile(""))
        end)
    end)

    describe("writeFile", function()
        it("writes text to a file", function()
            assert.is_true(FileUtil.writeFile(dir .. "/version.txt", "0.4"))
            assert.are.equal("0.4", helper.readFile(dir .. "/version.txt"))
        end)

        it("refuses nil content and invalid paths", function()
            assert.is_false(FileUtil.writeFile(dir .. "/version.txt", nil))
            assert.is_false(FileUtil.writeFile(nil, "0.4"))
            assert.is_false(helper.exists(dir .. "/version.txt"))
        end)

        it("returns false when the file cannot be opened", function()
            assert.is_false(FileUtil.writeFile(dir .. "/missing/version.txt", "0.4"))
        end)
    end)

    describe("removeFile", function()
        it("deletes the file", function()
            helper.writeFile(dir .. "/book.epub", "data")
            FileUtil.removeFile(dir .. "/book.epub")
            assert.is_false(helper.exists(dir .. "/book.epub"))
        end)

        it("ignores invalid paths", function()
            FileUtil.removeFile(nil)
            FileUtil.removeFile("")
        end)
    end)

    describe("isValidFile / isValidDirectory", function()
        it("tells files and directories apart", function()
            helper.writeFile(dir .. "/book.epub", "data")
            assert.is_true(FileUtil.isValidFile(dir .. "/book.epub"))
            assert.is_false(FileUtil.isValidFile(dir))
            assert.is_true(FileUtil.isValidDirectory(dir))
            assert.is_false(FileUtil.isValidDirectory(dir .. "/book.epub"))
            assert.is_false(FileUtil.isValidFile(dir .. "/missing.epub"))
        end)

        it("rejects invalid paths", function()
            assert.falsy((FileUtil.isValidFile(nil)))
            assert.falsy((FileUtil.isValidDirectory("")))
        end)
    end)
end)
